Step3-kakao-tech-campus/Team9_BE

linknamu/src/main/java/com/kakao/linknamu/Bookmark/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/Bookmark/BookmarkJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/BookmarkTagJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/Bookmark_Tag.java
linknamu/src/main/java/com/kakao/linknamu/Category/Category.java
linknamu/src/main/java/com/kakao/linknamu/Category/CategoryJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/Tag/Tag.java
linknamu/src/main/java/com/kakao/linknamu/Tag/TagJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/User/User.java
linknamu/src/main/java/com/kakao/linknamu/User/UserJPARepository.java

- 환경 설정 완료된 Weekly 브랜치 포크해서 작업했음
- ERD를 참고하여 Bookmark, Bookmark_Tag, Category, Tag, User 엔티티 구현했음
- JPARepositry도 작성하려 했으나 어떤 쿼리가 필요하게 될지는 API설계 단계에서 고민해야 할 듯 하여 파일 생성까지만 진행함

ERD를 기반으로 JPA 엔티티 구현

---

linknamu/src/main/java/com/kakao/linknamu/Bookmark/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/BookmarkTag.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/BookmarkTagId.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/BookmarkTagJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/BookmarkTag/Bookmark_Tag.java
linknamu/src/main/java/com/kakao/linknamu/Category/Category.java
linknamu/src/main/java/com/kakao/linknamu/Tag/Tag.java

- @Column 및 @JoinColumn병행으로 발생한 에러 수정
- @EmbeddedId를 사용하도록 코드 수정
- @EmbeddedId를 사용하게 되면서 불필요해진 unique 제약조건 삭제
- hash 및 equals 추가
- Java Convention에 맞도록 파일 명 수정

fix: ERD 기반 JPA 엔티티 구현에서 시스템 실행 시 발생한 에러 수정

---

linknamu/src/main/java/com/kakao/linknamu/category/CategoryExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/category/controller/CategoryController.java
linknamu/src/main/java/com/kakao/linknamu/category/dto/CategoryDetailResponseDto.java
linknamu/src/main/java/com/kakao/linknamu/category/dto/CategoryListResponseDto.java
linknamu/src/main/java/com/kakao/linknamu/category/dto/ChildCategoryListResponseDto.java
linknamu/src/main/java/com/kakao/linknamu/category/dto/PageInfoDto.java
linknamu/src/main/java/com/kakao/linknamu/category/repository/CategoryJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryListService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryReadService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java

close #25 
- 카테고리 리스트 조회 API
- 자녀 카테고리 리스트 조회 API
- 카테고리 추가 API에서 Exception403 예외처리 코드 추가

#25 카테고리 조회하기 API 구현

---

linknamu/src/main/java/com/kakao/linknamu/_core/config/JpaConfig.java
linknamu/src/main/java/com/kakao/linknamu/_core/util/AuditingEntity.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/entity/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/bookmarkTag/BookmarkTag.java
linknamu/src/main/java/com/kakao/linknamu/category/entity/Category.java
linknamu/src/main/java/com/kakao/linknamu/tag/entity/Tag.java
linknamu/src/main/java/com/kakao/linknamu/user/controller/DevSocialLoginController.java
linknamu/src/main/java/com/kakao/linknamu/user/entity/User.java
linknamu/src/main/java/com/kakao/linknamu/user/service/UserService.java
linknamu/src/test/java/com/kakao/linknamu/user/controller/GoogleLoginControllerTest.java
linknamu/src/test/java/com/kakao/linknamu/user/service/UserServiceTest.java

close #35
---
다음과 같은 작업을 진행했습니다.
- 회원가입 시 루트 카테고리 생성
- 엔티티 생성일자, 수정일자 추가 (Auditing Entity)
- properties 문제 수정

#35 회원가입 시 루트 카테고리 생성 기능 추가

---

linknamu/src/main/java/com/kakao/linknamu/category/repository/CategoryJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategorySaveService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java

- DataJPA에서 @Param을 사용하지 않아 발생하는 에러 수정
- CategoryService에 있던 save 유효성 검사를 CategorySaveService로 이동

HotFix: Merge 후 발생한 에러에 대한 긴급수정

---

linknamu/src/main/java/com/kakao/linknamu/category/CategoryExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/category/controller/CategoryController.java
linknamu/src/main/java/com/kakao/linknamu/category/dto/CategoryUpdateRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/category/entity/Category.java
linknamu/src/main/java/com/kakao/linknamu/category/repository/CategoryJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryUpdateService.java

#26 카테고리 수정하기 API 구현

---

linknamu/src/main/java/com/kakao/linknamu/category/CategoryExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/category/controller/CategoryController.java
linknamu/src/main/java/com/kakao/linknamu/category/entity/Category.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryReadService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategorySaveService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryUpdateService.java

close #27 
- 카테고리 삭제 API 구현
- 유저 불일치 예외처리 메서드 분리 및 update, delete에 적용
- 카테고리 저장 시 카테고리 이름 중복 확인 코드 추가

#27 카테고리 삭제하기 API 구현

---

linknamu/src/main/java/com/kakao/linknamu/category/CategoryExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryDeleteService.java

- delete 에서 부모 카테고리와 카테고리 아이디가 같은 경우 400에러 던지도록 수정했습니다.

#27 루트 카테고리 삭제 예외처리

---

.github/workflows/test-ci.yml
.idea/.gitignore
.idea/Team9_BE.iml
.idea/compiler.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml

우선 gradlew test 만 검증하고, 테스트통과하면 바로 워크플로우 성공했다고 해놨습니다.

#41 Chore: 깃허브 액션 워크플로우 야믈 파일 작성

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/entity/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/repository/BookmarkJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkCreateService.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkUpdateService.java
linknamu/src/main/java/com/kakao/linknamu/bookmarkTag/entity/BookmarkTag.java
linknamu/src/main/java/com/kakao/linknamu/category/controller/CategoryController.java
linknamu/src/main/java/com/kakao/linknamu/category/entity/Category.java
linknamu/src/main/java/com/kakao/linknamu/category/repository/CategoryJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryReadService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategorySaveService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryUpdateService.java
linknamu/src/main/java/com/kakao/linknamu/tag/entity/Tag.java
linknamu/src/main/java/com/kakao/linknamu/user/service/UserService.java
linknamu/src/main/java/com/kakao/linknamu/workspace/WorkspaceExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/workspace/entity/Workspace.java
linknamu/src/main/java/com/kakao/linknamu/workspace/repository/WorkspaceJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceSaveService.java
linknamu/src/test/java/com/kakao/linknamu/bookmark/repository/BookmarkJPARepositoryTest.java
linknamu/src/test/java/com/kakao/linknamu/bookmarkTag/repository/BookmarkTagJPARepositoryTest.java
linknamu/src/test/java/com/kakao/linknamu/category/CategoryJPARepositoryTest.java
linknamu/src/test/java/com/kakao/linknamu/user/controller/GoogleLoginControllerTest.java
linknamu/src/test/java/com/kakao/linknamu/user/service/UserServiceTest.java

closed #68
- 워크스페이스 엔티티 추가
- 카테고리 엔티티 수정
- 워크스페이스 , 카테고리 엔티티 추가 및 수정으로 인해 변경된 코드를 주석 및 수정

#68 워크스페이스 엔티티 추가

---

.github/workflows/test-ci.yml
.gitignore
.idea/.gitignore
.idea/compiler.xml
.idea/misc.xml
.idea/modules.xml
linknamu/.gitignore
linknamu/build.gradle
linknamu/src/main/resources/application-local.yml

깃허브 액션 적용 #41 
깃허브 액션 워크플로우 야믈 파일 작성했습니다.
도커 어떻게 올리지 고민하면서 
```
- name: Start Redis Container
run: |
docker pull redis:alpine
docker run -d --name redis-container -p 6379:6379 redis:alpine
- name: Run Your Tests with Redis
run: |
- name: Stop Redis Container
run: |
docker stop redis-container
docker rm redis-container
```
이런식으로 적용해보려 했는데 그냥 gradlew 테스트를 돌려도 테스트가 전부 돌아가네요....
말씀하신대로 바로 weekly 브랜치로 pr날리겠습니다.

#41 깃허브 액션 워크플로우 작성 완료

---

linknamu/src/main/java/com/kakao/linknamu/workspace/WorkspaceExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/workspace/controller/WorkspaceController.java
linknamu/src/main/java/com/kakao/linknamu/workspace/dto/WorkspaceCreateRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/workspace/dto/WorkspaceGetResponseDto.java
linknamu/src/main/java/com/kakao/linknamu/workspace/dto/WorkspaceUpdateRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/workspace/entity/Workspace.java
linknamu/src/main/java/com/kakao/linknamu/workspace/repository/WorkspaceJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceReadService.java
linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceUpdateService.java

테스트 코드는 이후 작성하겠습니다.
---
- #69 
- #70 
- #71 
- #78 
---
close #69 #70 #71 #78

워크스페이스 API 구현

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDto.java

- #59 
북마크 추가 dto의 categoryId항목에 @NotNull 어노테이션을 추가했습니다.

북마크 추가 dto 어노테이션 수정

---

linknamu/src/main/java/com/kakao/linknamu/kakao/service/KaKaoSendMeService.java

regex 를 약간 수정했습니다.
tld가 최소 규정이 1자리로 알고 있지만, 한번도 본적이 없기 떄문에
2자리 이상부터 검출되도록 했습니다.
추후에 금방 변경 가능하니 이점 참고 바랍니다.

#63 Fix: regex 수정

---

linknamu/src/main/java/com/kakao/linknamu/_core/config/HttpConnectionConfig.java
linknamu/src/main/java/com/kakao/linknamu/_core/redis/RedisExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/_core/security/JwtExceptionFilter.java

close #85 
- RestTemplate connection timeout 설정
- JwtException status code 수정

#85 4주차 PR 코드 리뷰 피드백을 토대로 코드 수정

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/bookmarkTag/entity/BookmarkTag.java

close #91 
- 북마크 삭제 시 외래키 제약조건에 의해 삭제되지 않는 문제를 해결했습니다.

#91 북마크 삭제 시 발생하는 에러를 수정 해결.

---

linknamu/.gitignore
linknamu/src/main/java/com/kakao/linknamu/_core/util/AuditingEntity.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/entity/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkDeleteService.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkMoveService.java

close #100
- 북마크 생성 시 정규표현식이 잘못돼 제대로된 url에 예외처리 시키는 문제를 해결했습니다.
- 북마크 이동 시 발생하는 에러를 수정했습니다.

#100 북마크 생성, 북마크 이동 오류 수정

---

linknamu/src/main/java/com/kakao/linknamu/_core/config/HttpConnectionConfig.java
linknamu/src/main/java/com/kakao/linknamu/_core/exception/Exception502.java
linknamu/src/main/java/com/kakao/linknamu/_core/exception/GlobalExceptionHandler.java
linknamu/src/main/java/com/kakao/linknamu/_core/security/CustomUserDetailsService.java
linknamu/src/main/java/com/kakao/linknamu/_core/security/SecurityConfig.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkDeleteService.java

close #115 
- HttpConnection ReadTimeout 주석 해제
- Exception502에 대한 구분 추가 (Bad Gateway)
- 사용하지 않는 주석 제거 (GlobalException -> // log.error(...) )
- CustomUserDetailsService에서 Exception에 대한 에러 코드 정의 설정
- SecurityConfig에서 주석된 권한 부분 삭제

#115 5주차 코드 리뷰 사항 수정

---

linknamu/docker-compose-stage.yml
linknamu/src/main/java/com/kakao/linknamu/notion/service/NotionApiBatchService.java

close #105 
- 북마크 및 임베드 링크또한 읽을 수 있도록 로직을 변경했습니다.

#105 다양한 노션 링크 종류 추출 구현

---

linknamu/src/test/java/com/kakao/linknamu/_core/TestConfig.java
linknamu/src/test/java/com/kakao/linknamu/workspace/controller/WorkspaceControllerTest.java
linknamu/src/test/java/com/kakao/linknamu/workspace/repository/WorkspaceJpaRepositoryTest.java
linknamu/src/test/java/com/kakao/linknamu/workspace/service/WorkspaceDeleteServiceTest.java
linknamu/src/test/java/com/kakao/linknamu/workspace/service/WorkspaceReadServiceTest.java
linknamu/src/test/java/com/kakao/linknamu/workspace/service/WorkspaceSaveServiceTest.java
linknamu/src/test/java/com/kakao/linknamu/workspace/service/WorkspaceUpdateServiceTest.java

- 워크스페이스 레포지토리 테스트 작성
- 워크스페이스 서비스 테스트 작성
- 워크스페이스 컨트롤러 테스트 작성 (성공 케이스)

#126 워크스페이스 테스트 코드 작성

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/controller/BookmarkController.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkResponseDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkUserQueryDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/repository/BookmarkJPARepository.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkCreateService.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkReadService.java

close #136
- 북마크 단일 조회 API 추가
- 북마크 생성 로직 중 태그 저장 버그 수정

#136 북마크 단일 조회 API 추가

---

linknamu/src/main/java/com/kakao/linknamu/_core/config/FilterConfig.java
linknamu/src/main/java/com/kakao/linknamu/_core/filter/LoggingFilter.java
linknamu/src/main/resources/logback.xml

close #140 
- LoggingFilter 구현
- 로그 파일 생성을 위한 logback.xml 구현
- http method, uri, status code, request body만 로그에 출력되도록 수정했습니다.
- 로그인 api에서 토큰이 로그에 노출될 일이 없어 따로 처리하지 않았습니다.

#140 로깅 구현

---

Dockerfile
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkCreateService.java
linknamu/src/main/java/com/kakao/linknamu/googleDocs/service/GoogleDocsApiBatchService.java
linknamu/src/main/java/com/kakao/linknamu/notion/service/NotionApiBatchService.java
linknamu/src/main/resources/application-prod.yml

- 환경변수 기반 설정 추가
- Jsoup 프록시 적용
- Transactional(readonly=true) 버그 픽스

#149 환경변수 등록 및 버그 픽스

---

linknamu/src/main/java/com/kakao/linknamu/share/service/category/CreateLinkFromCategoryService.java
linknamu/src/main/java/com/kakao/linknamu/share/service/workspace/CreateLinkFromWorkspaceService.java

- 기존 도메인까지 응답하던 방식에서 url만 응답하는 방식으로 변경했습니다.

Mod: URI 출력 형식 변경

---

README.md

#189 README.md 파일 수정

---

linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceUpdateService.java

- 워크스페이스 수정시 수정하는 워크스페이스 이름이 중복될 경우 예외가 발생하도록 버그를 수정했습니다.

Fix: 워크스페이스 수정 API 에러 수정

---

linknamu/build.gradle
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkCreateService.java
linknamu/src/main/java/com/kakao/linknamu/core/config/S3Config.java
linknamu/src/main/java/com/kakao/linknamu/core/config/S3ConfigProxy.java
linknamu/src/main/java/com/kakao/linknamu/core/exception/GlobalExceptionHandler.java
linknamu/src/main/java/com/kakao/linknamu/core/util/S3ImageClient.java
linknamu/src/main/java/com/kakao/linknamu/core/util/UtilExceptionStatus.java
linknamu/src/main/java/com/kakao/linknamu/kakao/service/KaKaoSendMeExtractService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/utils/JsoupUtils.java
linknamu/src/main/java/com/kakao/linknamu/user/UserExceptionStatus.java
linknamu/src/main/resources/application-local.yml
linknamu/src/main/resources/application-test.yml

base64로 암호화된 imgURL을 복호화해서 s3에  업로드 한후 해당 s3 url주소를 return 로직 구현
만약 암호화된 url이 없으면 => 북마크 링크의 메타데이터 접근 통해 썸네일링크 return
메타데이터 접근 실패시나 썸네일이 없을 경우 => s3에 저장해놓은 default image url을 return

Feat: s3 이미지 업로드 기능 구현

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkCreateService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/googledocs/service/GoogleDocsApiBatchService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/notion/service/NotionApiBatchService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/utils/JsoupResult.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/utils/JsoupUtils.java
linknamu/src/main/resources/application-local.yml
linknamu/src/main/resources/application-prod.yml

- S3 적용 후 노션, 구글 독스 연동에 대해서도 메타데이터 추출 후 이미지를 저장하는 코드를 추가했습니다.

Feat: 연동 시스템 이미지 링크 추가 구현

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/repository/BookmarkJpaRepository.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkService.java
linknamu/src/main/java/com/kakao/linknamu/bookmarktag/service/BookmarkTagService.java
linknamu/src/main/java/com/kakao/linknamu/category/service/CategoryService.java
linknamu/src/main/java/com/kakao/linknamu/share/service/category/ShareCategoryService.java
linknamu/src/main/java/com/kakao/linknamu/share/service/workspace/ShareWorkspaceService.java
linknamu/src/main/java/com/kakao/linknamu/tag/service/TagService.java
linknamu/src/main/java/com/kakao/linknamu/workspace/service/WorkspaceService.java

- 트랜잭션 설정이 맞지 않은 점을 수정했습니다.
- 북마크 수정 시 @Modifying에 flush, clear 자동화를 추가했습니다.
- 조회 메소드에서 조건에 따라 생성로직을 동작하는 것을 분리했습니다.

#175 서비스 코드 통합 코드 수정

---

linknamu/src/main/java/com/kakao/linknamu/core/util/S3ImageClient.java
linknamu/src/main/java/com/kakao/linknamu/core/util/UtilExceptionStatus.java

Base64로 인코딩된 이미지 파일 과
이미지 링크 를 모두 처리하는 로직 구현

북마크 추가하기 API 기능 구현

---

linknamu/src/main/java/com/kakao/linknamu/core/exception/Exception404.java

- 404에러가 401로 출력되는 버그를 수정했습니다.

HotFix: 404 에러코드 수정

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkSearchCondition.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/validator/SearchCheck.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/validator/SearchCheckValidator.java

- 단일 필드에 대해서만 검증해 오류가 발생하는 문제를 다중 필드로 변경하는 방식으로 해결했습니다.

Fix: Dto 다중 필드 Validator추가

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkService.java

- 북마크들을 공유하는 과정에서 태그까지 공유되는 버그를 수정했습니다.

Fix: 공유 API 중 태그까지 공유되는 버그 수정

---

linknamu/src/main/java/com/kakao/linknamu/bookmark/controller/BookmarkController.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/dto/BookmarkRequestDto.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/entity/Bookmark.java
linknamu/src/main/java/com/kakao/linknamu/bookmark/service/BookmarkService.java
linknamu/src/main/java/com/kakao/linknamu/core/util/S3ImageClient.java

- 북마크 이미지 수정 API를 구현했습니다.
- 북마크 수정 시 입력되는 Dto에 검증을 추가했습니다.

Feat: 북마크 이미지 수정 API 구현

---

linknamu/build.gradle
linknamu/src/main/java/com/kakao/linknamu/core/kafka/consumer/GoogleDocsConsumer.java
linknamu/src/main/java/com/kakao/linknamu/core/kafka/consumer/KakaoConsumer.java
linknamu/src/main/java/com/kakao/linknamu/core/kafka/consumer/NotionConsumer.java
linknamu/src/main/java/com/kakao/linknamu/core/util/KafkaTopics.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/googledocs/service/GoogleDocsApiBatchService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/googledocs/service/GoogleDocsApiService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/googledocs/util/GoogleDocsProvider.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/notion/dto/NotionKafkaReqeusetDto.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/notion/service/NotionApiBatchService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/notion/service/NotionApiService.java
linknamu/src/main/java/com/kakao/linknamu/thirdparty/notion/util/NotionProvider.java
linknamu/src/main/java/com/kakao/linknamu/workspace/dto/WorkspaceCreateRequestDto.java
linknamu/src/main/resources/application-local.yml
linknamu/src/main/resources/application-prod.yml

- 카프카 연동 설정을 추가했습니다.
- 노션, 구글 독스를 처음 생성 시 링크를 가져오는 과정을 카프카에 이벤트를 보내 다른 쓰레드에서 처리할 수 있도록 기능을 추가했습니다.

Feat: 카프카 추가 및 연동
